- name: logentries rsyslog
  copy:
    src: logentries.conf
    dest: /etc/rsyslog.d/

- name: docker service                                                             
  service:                                                                         
    name: docker                                                                   
    state: started

- name: pull images
  docker_image:
    name: "{{item}}"
  with_items:
    - mergermarket/docker-logentries
    - mergermarket/mmg-logspout
